In [2]:
import cv2
import numpy as np
import time
import argparse

In [3]:
cap = cv2.VideoCapture("Input.mp4")


In [4]:
for i in range(60):
	ret,background = cap.read()

In [5]:
print(background)

[[[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 ...

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]]


In [6]:
print(ret)

True


In [7]:
ret, img = cap.read()

In [8]:
print(ret, img)

True [[[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 ...

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]
  ...
  [0 0 1]
  [0 0 1]
  [0 0 1]]]


In [9]:
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
print(hsv)

[[[  0 255   1]
  [  0 255   1]
  [  0 255   1]
  ...
  [  0 255   1]
  [  0 255   1]
  [  0 255   1]]

 [[  0 255   1]
  [  0 255   1]
  [  0 255   1]
  ...
  [  0 255   1]
  [  0 255   1]
  [  0 255   1]]

 [[  0 255   1]
  [  0 255   1]
  [  0 255   1]
  ...
  [  0 255   1]
  [  0 255   1]
  [  0 255   1]]

 ...

 [[  0 255   1]
  [  0 255   1]
  [  0 255   1]
  ...
  [  0 255   1]
  [  0 255   1]
  [  0 255   1]]

 [[  0 255   1]
  [  0 255   1]
  [  0 255   1]
  ...
  [  0 255   1]
  [  0 255   1]
  [  0 255   1]]

 [[  0 255   1]
  [  0 255   1]
  [  0 255   1]
  ...
  [  0 255   1]
  [  0 255   1]
  [  0 255   1]]]


In [10]:
print(img.size)

2764800


In [11]:
print(img.shape)

(720, 1280, 3)


In [12]:
img.width

AttributeError: 'numpy.ndarray' object has no attribute 'width'

In [13]:
height, width, channels = img.shape

In [14]:
height

720